HomeApp/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
app_name = "main"

urlpatterns = [

    path('', views.MainHome, name='MainHome'),
    path('details/<int:id>/',views.detail,name='detail'),
    path('addreview/<int:id>/', views.add_review, name='add_review')
]

movieapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls'), name='MainHome'),
]

HomeApp/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Movie(models.Model):
    #fields for the movie table
    name = models.CharField(max_length=1000)
    director = models.CharField(max_length=100)
    cast = models.CharField(max_length=1000)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField()
    image = models.URLField(default = None , null = True)

    def __str__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

HomeApp/forms.py
from django import forms
from .models import *


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment" , "rating")

HomeApp/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def MainHome(request):
    query = request.GET.get("title")
    allMovies = None
    if query :
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()    
    
    context = {
        #value : object variable
        "movies" : allMovies,
    }
    return render(request, 'main/index.html' , context)

def detail(request, id):
    movie = Movie.objects.get(id=id) #selects * from movie where id=id
    reviews = Review.objects.filter(movie=id).order_by("-comment")

    context={
        "movie" : movie,
        "reviews" : reviews
    }

    return render(request , 'main/details.html', context)

def add_review(request, id):
    if request.user.is_authenticated :
        movie = Movie.objects.get(id=id)    
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("main:detail" , id)

        else:
            form = ReviewForm()

        return render(request, 'main/details.html' , {"form" : form}) 

      

HomeApp/templates/main/base.html
<!doctype html>
<html lang="en">
    
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link rel ="stylesheet" href = "{% static 'css/main.css' %}">
    <title>MovieReview</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-whites">
        <a class="navbar-brand" href="#">Movie Review</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            
          </ul>
          <form class="form-inline my-2 my-lg-0" >
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name = "title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    {% block content %}



    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

HomeApp/templates/main/details.html
{%extends 'main/base.html '%}

{%block content%}


<div class = "container">
    <br>
    <div class = "card">
        <div class = "card-body">
        <div class = "row">
            <div class = "col-md-4">
                <img src = "{{ movie.image }}" alt = "{{ movie.name }}" class = "img-fluid">
            </div>
            <div class = "col-md-8">
                <h3 class = "text-center">
                    {{movie.name}}
                </h3>
                <p>{{ movie.description }}</p>
                <h5>Director: {{ movie.director }}</h5>
                <h5>cast: {{ movie.cast }}</h5>
                <h5>Rating: {{ movie.averageRating }}</h5>
            </div>
        </div>
    </div>
    
    </div>
    <br>
    <div class = "card">
        <div class = "card-body">
            <h3 class = "text-center"> Reviews </h3>
            <form action ="{% url 'main:add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>
                <label for="rating">Rating</label>
                <input type = "text" name = "rating" class="form-control">

                <br>
                <input type = "submit"  class="btn btn-danger" value="Add Review">


            </form>
        </div>
    </div>
    <br>
    <div class = "card">
        <div class = "card-body">
            <h3 class="text-center"> Comments </h3>
            {% for review in reviews%}
                <div class = "card">
                    <div class = "card-body">
                        <div class = "row">
                            <div class = "col-md-3">
                                <h5 class = "text-left"> {{ review.user.username }} </h5>
                                <h5>{{ review.rating }}</h5>

                            </div>
                            <div class = "col-md-9">
                                <p>{{ review.comment }}</p>
                                
                            </div>
                        </div>
                    </div>

                </div>
                <br>
                {% endfor %}

            
        </div>

    </div>
        
</div>


{%endblock%}

HomeApp/templates/main/index.html
{%extends 'main/base.html'%}

{%block content%}

<div class = "container">
  <br>
  <div class = "card" id ="backdrop">
    <div class = "card-body"> 
      <div class = "row">
        {%for movie in movies%}
        <div class ="col-md-4">
          <div class = "card">
            <div class = "card-body">
              <div class = "text-center">
                <img src ="{{ movie.image}}" alt="" class="img-fluid" width="75%">
                <h3 class = "text-center">{{ movie.name }}</h3>
              
                <i class = "text-center">{{ movie.release_date}}</i>
                <a href = "{% url 'main:detail' movie.id %}"> Read More </a>
              
              </div>
            </div>
          </div>
          
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>



{%endblock%}